### ISSUE TITLE
References

### ISSUE THREAD

**Issue by lanyin1997** [CindiFeng/NMPC-SlungLoadQuad#1]
Could you send us links to references? Thank you very much!

**Comment by CindiFeng** [comment]
Nikhil D. Potdar, Guido C. H. E. de Croon, and Javier Alonso-Mora. Online trajectory planning and control of a mav payload system in dynamic environments. Autonomous Robots, 44:1065–1089, 7 2020

**Comment by lanyin1997** [comment]
Thank you for your reply，but I failed to run your open source code, an error occurs while running main.m file:
In standard cost function, zero weights are applied by default to one or more OVs because there are fewer MVs than OVs.
Function or variable 'CostFcn' is not recognized.

Error znlmpc_getZBounds (line 36)
    f1 = hCostFcn(X0, U0, e0, userdata, runtimedata.Parameters{:});

Error nlmpc/nlmpcmove (Line 122)    [zLB, zUB] = znlmpc_getZBounds(coredata, runtimedata, userdata, handles.hCostFcn, z0);

Error main (line 150)
[~,~,info] = nlmpcmove(nlobj,x0,u0,terminal,[],nloptions);
 My MATLAB version is 2021b, so I would like to ask if there is a solution.
Thank you for taking time out of your busy schedule to reply me. I wish you good health and success in your work!
