### ISSUE TITLE
Hello, can I use the NMPC module in Simulink for robot trajectory planning?

### ISSUE THREAD

**Issue by Jasoncnnn** [CindiFeng/NMPC-SlungLoadQuad#2]
Hello, I need to use NMPC in Simulink to plan the trajectory of the robot, which includes a four wheel chassis and a six axis robotic arm. May I ask if there are any similar tutorials or blogs that I can refer to?Thanks.

**Comment by CindiFeng** [comment]
There should be several on MATLAB. This current project does not support direct use with Simulink (will need to change a few files for this simulink connection to establish).

**Comment by CindiFeng** [comment]
There should be several on MATLAB. This current project does not support direct use with Simulink (will need to change a few files for this simulink connection to establish).
